name: Cypress Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  # Permite execução manual a partir da aba Actions no GitHub
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      # Quando um teste falha, os outros continuam executando
      fail-fast: false
      matrix:
        # Executa em diferentes navegadores
        browsers: [chrome, firefox]
        # Você pode adicionar mais configurações aqui, como diferentes ambientes
        # environments: [staging, production]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Instalar dependências
        run: npm ci
      
      - name: Verificar cypress
        run: npx cypress verify
        
      - name: Executar testes Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browsers }}
          # Se você tiver diferentes scripts de teste, especifique aqui
          # command: npm run test:e2e
      
      - name: Armazenar screenshots em caso de falha
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browsers }}
          path: cypress/screenshots
          retention-days: 7