name: Cypress Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  # Permite execução manual a partir da aba Actions no GitHub
  workflow_dispatch:
    inputs:
      spec:
        description: 'Arquivo de teste específico para executar (ex: cypress/e2e/Financeiro/fluxo.cy.js)'
        required: false
        default: 'cypress/e2e/Financeiro/fluxo.cy.js'
      environment:
        description: 'Ambiente para executar os testes (staging, homolog, producao)'
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - homolog
          - producao

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    # Condicional: executa apenas se for acionado manualmente ou para eventos automáticos
    # Se for manual, passa o ambiente do input, caso contrário usa a matriz
    strategy:
      # Quando um teste falha, os outros continuam executando
      fail-fast: false
      matrix:
        # Executa apenas em Chrome para simplificar
        browsers: [chrome]
        # Define ambientes disponíveis para execução automática
        environment: [staging]
        
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Instalar dependências
        run: npm ci
      
      - name: Verificar cypress
        run: npx cypress verify
        
      - name: Executar testes Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browsers }}
          command: npm run cypress:run:${{ github.event.inputs.environment || matrix.environment }} -- --spec "cypress/e2e/Financeiro/fluxo.cy.js"
        env:
          CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
          CYPRESS_DEFAULT_TIMEOUT: 30000
          CYPRESS_RETRIES: 2
      
      - name: Armazenar screenshots em caso de falha
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browsers }}
          path: cypress/screenshots
          retention-days: 7