name: Cypress Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  # Permite execução manual a partir da aba Actions no GitHub
  workflow_dispatch:
    inputs:
      spec:
        description: 'Arquivo de teste específico para executar (ex: cypress/e2e/login.cy.js)'
        required: false
        default: 'cypress/e2e/**/*.cy.js'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      # Quando um teste falha, os outros continuam executando
      fail-fast: false
      matrix:
        # Executa em diferentes navegadores
        browsers: [chrome, firefox]
        # Você pode adicionar mais configurações aqui, como diferentes ambientes
        # environments: [staging, production]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Instalar dependências
        run: npm ci
      
      - name: Verificar cypress
        run: npx cypress verify
        
      - name: Listar arquivos para depuração
        run: |
          ls -la
          ls -la cypress/
          ls -la cypress/e2e/ || echo "Directory e2e not found"
          
      - name: Executar testes Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browsers }}
          spec: "./cypress/e2e/fluxo.cy.js"
          working-directory: ./
          # Usando comando personalizado
          command: npx cypress run --spec "cypress/e2e/fluxo.cy.js"
      
      - name: Armazenar screenshots em caso de falha
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browsers }}
          path: cypress/screenshots
          retention-days: 7